sudo: false
language: python
os:
  - linux
stages:
  - pylint
  - tests-python
jobs:
  include:
    - stage: pylint
      python: 3.6
      env: TOXENV=pylint
    - stage: tests-python
      python:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
install: pip install tox-travis
script: tox
jobs:
  allow_failures:
    - python: "3.8"